---
title: "Bedreiging-door-nieuwe-uitheemse-diersoorten"
author: "Dieter Sneyders"
date: "21 November, 2016"
output:
  html_document: 
    css: 'css/base.css'
  pdf_document: default
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# run to html with command:
#rmarkdown::render("bedreiging-door-nieuwe-uitheemse-diersoorten.Rmd", output_file = "../test/html/bedreiging-door-nieuwe-uitheemse-diersoorten.html")
#source("uitheemse-dieren.R")
#library(INBOtheme)


```

## Informatie {.tabset}

### Testdata

```{r, out.extra = 'angle=-90',fig.width=12, fig.height=13,echo = TRUE, message = TRUE, warning = TRUE}

for (i in 1:length(data_information)) {
  print(data_information[[i]]$name)
  print(data_information[[i]]$language.dutch())
  print(data_information[[i]]$language.english())
}


```

### Subcategories integrated 


```{r, out.extra = 'angle=-90', echo = FALSE, fig.width=12, fig.height=13, message = FALSE, warning = FALSE}
# ISSUE: figure need to be turned 90 degrees... ok in pdf, not in html

# Create the graph with subcategories

subcategoriesIntegrated
```

### Only categories

English version
```{r, out.extra = 'angle=-90', echo = FALSE, fig.width=12, fig.height=13, message = FALSE, warning = FALSE}
# ISSUE: figure need to be turned 90 degrees... ok in pdf, not in html

# Create the graph with subcategories
subcategoriesIntegratedEnglish
```

Nederlandse versie
```{r, out.extra = 'angle=-90', echo = FALSE, fig.width=12, fig.height=13, message = FALSE, warning = FALSE}
# ISSUE: figure need to be turned 90 degrees... ok in pdf, not in html

# Create the graph with subcategories
ggplot(df_pathway,  aes(x = reorder(category_nl, freq, function(x){sum(x)}),
                    y = freq, fill = kingdom)) +
    geom_bar(stat = "summary", fun.y = sum,
             width = .65) + 
    xlab("Introductieweg") +
    ylab("Aantal soorten") + 
    coord_flip() +
    scale_fill_discrete(labels = c("Dieren", "Planten"), 
                        breaks = c("Animalia", "Plantae")) + 
    theme(legend.position = "top",
          legend.title = element_blank()
          )
```



### Cumulative number of species in time 

English version
```{r, echo=FALSE, fig.width=9, fig.height=14, warning = FALSE, message = FALSE}
cumulativeSpeciesEnglish
```

Dutch version
```{r, echo=FALSE, fig.width=9, fig.height=14, warning = FALSE, message = FALSE}

cumulativeSpecies
```





